package com.clairvoyance.bookmarket;

import com.google.firebase.database.Exclude;
import com.google.firebase.database.IgnoreExtraProperties;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * Created by Sathya on 12/21/2017.
 *
 */

@IgnoreExtraProperties
class User implements Serializable {
    private String name;
    private String uid;
    private String email;
    private ArrayList<Post> myPosts = new ArrayList<>();
    private ArrayList<String> postIDs = new ArrayList<>();
    private boolean isEmailVerified = false;

    public User(){

    }

    User(String uid, String email){
        this.uid = uid;
        this.email = email;
        myPosts = new ArrayList<>();
    }

    void setName(String name) {
        this.name = name;
    }
    String getName() {
        return name;
    }
    // Todo: @Exclude getUid
    String getUid() {
        return uid;
    }
    String getEmail() {
        return email;
    }
    void setEmailVerified(boolean emailVerified) { isEmailVerified = emailVerified; }
    boolean isEmailVerified() { return isEmailVerified;  }

    void addPost(Post post){
        myPosts.add(post);
        postIDs.add(post.getPostID());
    }
    public ArrayList<String> getPostIDs() {
        return postIDs;
    }

    @Exclude
    ArrayList<SellPost> getMySellPosts() {
        ArrayList<SellPost> sellPosts = new ArrayList<>();
        for (Post post : myPosts){
            if (post instanceof SellPost){
                sellPosts.add((SellPost) post);
            }
        }

        return sellPosts;
    }


    @Override
    public boolean equals(Object obj) {
        if (obj instanceof User){
            if (this.uid.equals(((User) obj).getUid())){
                return true; // This test should never be wrong in theory provided the uid is generated by Firebase
            }
        }

        return super.equals(obj);
    }
}
