package com.clairvoyance.bookmarket;

import com.google.firebase.database.IgnoreExtraProperties;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * Created by Sathya on 12/21/2017.
 *
 */

@IgnoreExtraProperties
class User implements Serializable {
    private String name;
    private String UID;
    private String email;
    private ArrayList<Post> myPosts;
    private boolean isEmailVerified = false;

    public User(){

    }

    User(String UID, String email){
        this.UID = UID;
        this.email = email;
        myPosts = new ArrayList<>();
    }

    void setName(String name) {
        this.name = name;
    }
    String getName() {
        return name;
    }
    String getUID() {
        return UID;
    }
    String getEmail() {
        return email;
    }
    void setEmailVerified(boolean emailVerified) { isEmailVerified = emailVerified; }
    boolean isEmailVerified() { return isEmailVerified;  }

    void addPost(Post post){
        myPosts.add(post);
    }
    ArrayList<SellPost> getMySellPosts() {
        ArrayList<SellPost> sellPosts = new ArrayList<>();
        for (Post post : myPosts){
            if (post instanceof SellPost){
                sellPosts.add((SellPost) post);
            }
        }

        return sellPosts;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof User){
            if (this.UID.equals(((User) obj).getUID())){
                return true; // This test should never be wrong in theory provided the UID is generated by Firebase
            }
        }

        return super.equals(obj);
    }
}
