package com.clairvoyance.bookmarket;

import com.google.firebase.database.Exclude;
import com.google.firebase.database.IgnoreExtraProperties;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Created by Sathya on 12/21/2017.
 *
 */

@IgnoreExtraProperties
class User implements Serializable {
    private String name;
    private String uid;
    private String email;
    private ArrayList<Book> books = new ArrayList<>();
    private HashMap<String, Object> bookIDs = new HashMap<>();
    private boolean isEmailVerified = false;

    public User(){

    }

    User(String uid, String email){
        this.uid = uid;
        this.email = email;
    }

    void setName(String name) {
        this.name = name;
    }
    String getName() {
        return name;
    }

    @Exclude
    String getUid() {
        return uid;
    }

    String getEmail() {
        return email;
    }
    void setEmailVerified(boolean emailVerified) { isEmailVerified = emailVerified; }
    boolean isEmailVerified() { return isEmailVerified;  }

    void addBook(Book book){
        books.add(book);
        bookIDs.put(book.getBookID(), true);
    }
    void addBookList(ArrayList<Book> books){
        this.books = books;
        for (Book book: books){
            bookIDs.put(book.getBookID(), true);
        }
    }
    public HashMap<String, Object> getBookIDs() {
        return bookIDs;
    }

    @Exclude
    ArrayList<Book> getBooks() {
        return books;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof User){
            if (this.uid.equals(((User) obj).getUid())){
                return true; // This test should never be wrong in theory provided the uid is generated by Firebase
            }
        }

        return super.equals(obj);
    }
}
